# Generated by Django 5.2.1 on 2025-05-30 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0002_loginactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
